### ISSUE TITLE
Upgrade to Typescript 2

### ISSUE THREAD

**Issue by alexmunda** [alexmunda/webpack-typescript-karma-starter#6]
- [ ] Upgrade the project to use Typescript 2.
- [ ] [Update the typings to use npm](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/)
- [ ] Validate by running 'npm test'

**Comment by aquibm** [comment]
Hey @alexmunda, I'd like to pick this one up thanks :)

**Comment by alexmunda** [comment]
Fixed with #9
